#docker-compose.yml
services:
  app:
    build: .
    container_name: python_app
    volumes:
      - images_data:/app/images
      - logs_data:/app/logs
    environment:
      - UPLOAD_DIR=/app/images
      - LOG_DIR=/app/logs
      - LOG_FILE_PATH=/app/logs/server.log
      - EXTERNAL_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=images_db
      - DB_USER=postgres
      - DB_PASSWORD=QazXsw1423!
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_server
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - images_data:/images:ro
      - ./src/static:/app/src/static:ro
      - ./src/form:/app/src/form:ro
    depends_on:
      - app
    networks:
      - app_network
    restart: always

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=images_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=QazXsw1423!
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d images_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: always

volumes:
  images_data:
  logs_data:
  db_data:

networks:
  app_network:
    driver: bridge